### ISSUE TITLE
Cannot find d2_kmeans software

### ISSUE THREAD

**Issue by stevewyl** [bobye/acl2017_document_clustering#1]
Hi. I searched google and GitHub but there is no package called d2_kmeans. If possible, could you give me the link for downloading this package? Thanks!

**Comment by bobye** [comment]
Hi @stevewyl 

The d2_kmeans package is a private repository I wrote about two years ago. I have not been quite maintaining this package for quite a while. I may share with you the whole package privately if you write me an email (with a brief introduction about yourself and why you need it).

Thanks.
